# Test Generated by Dashi
# 
# To use:
#  1. In the test directory create a Gemfile:
#      source "https://www.rubygems.org"
#      gem "selenium-web@driver"
#      gem "net-http-persistent"
#
#  2.  run `bundle update` in that directory
#  3.  set the 'SAUCE_USERNAME' & 'SAUCE_ACCESS_KEY' environment variables
#  4.  run `bundle exec ruby repro.rb`

require "selenium/webdriver"
require 'selenium/webdriver/remote/http/persistent'

@screenindex = 0
def screeny
  puts "Taking shot #{@screenindex} at #{Time.now}"

  @driver.save_screenshot("screenshot#{@screenindex}.png")
  puts "Done"
  @screenindex += 1
end

def un
  ENV["SAUCE_USERNAME"]
end

def ak
  ENV["SAUCE_ACCESS_KEY"]
end

def auth
  "#{un}:#{ak}"
end

def server 
  "ondemand.saucelabs.com"
end

def port
  80
end

def endpoint
  "#{server}:#{port}/wd/hub"
end

def auth_endpoint 
  "http://#{auth}@#{endpoint}"
end

def device_name
  device = ENV["DEVICE"] || 'iPhone'
  (device.eql? 'iPhone') ? 'iPhone Simulator' : 'iPad 2 Simulator'
end

def caps
  caps = {}
  caps['appiumVersion'] = '1.6.3'
  caps['deviceName'] = device_name
  caps['deviceOrientation'] = 'portrait'
  caps['platformVersion'] = '9.3'
  caps['platformName'] = 'iOS'
  caps['browserName'] = 'Safari' 
  caps['prerun'] = {executable: 'https://exposition-fairy.herokuapp.com/memory_script.py', background: true}

  caps['name'] = "A Test Made with Dashi"
 return caps
end

http_client = ::Selenium::WebDriver::Remote::Http::Persistent.new
http_client.timeout = 300 # Browser launch can take a while   

STDERR.puts "Booting #{device_name}."

@driver = Selenium::WebDriver.for :remote, :url => auth_endpoint, :desired_capabilities => caps, :http_client => http_client

STDERR.puts "Device booted; Beginning test."

@driver.get "http://garvan.mlc.com.au/"
element_1 = @driver.find_element :css, "body"

STDERR.puts "Loaded site"

advisor_field = nil
element_ready = false
attempts = 0
while (element_ready == false && attempts < 10)
  advisor_field = @driver.find_element :css, "*[id=\"global_find_advisers_field\"]"
  element_ready = advisor_field && advisor_field.enabled? && advisor_field.displayed?
  attempts += 1
  sleep 1 unless element_ready
end

advisor_field.clear 
advisor_field.send_keys "2060"

STDERR.puts "Waiting for autocomplete"

js_1 = nil
element_ready = false
attempts = 0
while (element_ready == false && attempts < 10)
  js_1 = (@driver.execute_script "try { return (function (cssSelector, searchText, using) {\n  using = using || document;\n\n  var elements = using.querySelectorAll(cssSelector);\n  var matches = [];\n  for (var i = 0; i < elements.length; ++i) {\n    var element = elements[i];\n    var elementText = element.textContent || element.innerText || '';\n    if (elementText.indexOf(searchText) > -1) {\n      matches.push(element);\n    }\n  }\n  return matches;\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }", ".ui-menu-item a","NORTH SYDNEY NSW, 2060",nil,".bootstrap-page-standard")[0]
  attempts += 1
  element_ready = (!js_1.nil?) && js_1.enabled? && js_1.displayed?

  sleep 1 unless element_ready
end

js_1.click

STDERR.puts "Looking for the Find an Adviser elements"

js_2 = nil
element_ready = false
attempts = 0
while (element_ready == false && attempts < 10)
  js_2 = (@driver.execute_script "try { return (function (cssSelector, searchText, using) {\n  using = using || document;\n\n  var elements = using.querySelectorAll(cssSelector);\n  var matches = [];\n  for (var i = 0; i < elements.length; ++i) {\n    var element = elements[i];\n    var elementText = element.textContent || element.innerText || '';\n    if (elementText.indexOf(searchText) > -1) {\n      matches.push(element);\n    }\n  }\n  return matches;\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }", ".bootstrap-title h1","Find an adviser",nil,".bootstrap-page-standard")[0]
  attempts += 1
  element_ready = (!js_2.nil?) && js_2.enabled?

  sleep 1 unless element_ready
end

element_26 = @driver.find_element :css, ".resultitem"
element_27 = element_26.displayed? 

STDERR.puts "About to execute transforms"

@driver.execute_script "var scrollWidth = document.documentElement.scrollWidth; var bodyScrollWidth = document.body.scrollWidth; var totalWidth = Math.max(scrollWidth, bodyScrollWidth); var clientHeight = document.documentElement.clientHeight; var bodyClientHeight = document.body.clientHeight; var scrollHeight = document.documentElement.scrollHeight; var bodyScrollHeight = document.body.scrollHeight; var maxDocElementHeight = Math.max(clientHeight, scrollHeight); var maxBodyHeight = Math.max(bodyClientHeight, bodyScrollHeight); var totalHeight = Math.max(maxDocElementHeight, maxBodyHeight); return [totalWidth, totalHeight];"
@driver.execute_script "var height = undefined; var width = undefined; if (window.innerHeight) { height = window.innerHeight; } else if (document.documentElement && document.documentElement.clientHeight) { height = document.documentElement.clientHeight; } else { var b = document.getElementsByTagName('body')[0]; if (b.clientHeight) {height = b.clientHeight;} }; if (window.innerWidth) { width = window.innerWidth; } else if (document.documentElement && document.documentElement.clientWidth) { width = document.documentElement.clientWidth; } else { var b = document.getElementsByTagName('body')[0]; if (b.clientWidth) { width = b.clientWidth;} }; return [width, height];"
@driver.execute_script "var scrollWidth = document.documentElement.scrollWidth; var bodyScrollWidth = document.body.scrollWidth; var totalWidth = Math.max(scrollWidth, bodyScrollWidth); var clientHeight = document.documentElement.clientHeight; var bodyClientHeight = document.body.clientHeight; var scrollHeight = document.documentElement.scrollHeight; var bodyScrollHeight = document.body.scrollHeight; var maxDocElementHeight = Math.max(clientHeight, scrollHeight); var maxBodyHeight = Math.max(bodyClientHeight, bodyScrollHeight); var totalHeight = Math.max(maxDocElementHeight, maxBodyHeight); return [totalWidth, totalHeight];"
@driver.execute_script "return window.devicePixelRatio"
@driver.execute_script "var origOverflow = document.documentElement.style.overflow; document.documentElement.style.overflow = \"hidden\"; return origOverflow"


screenindex = 0

puts @driver.execute_script "return { 'transform': document.documentElement.style['transform'],'-webkit-transform': document.documentElement.style['-webkit-transform'], }"
@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -0px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -0px)';"
puts "Taking shot #{screenindex}"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -325px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -325px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -650px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -650px)';"
screeny 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -975px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -975px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1300px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1300px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1625px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1625px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1950px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1950px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -2275px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -2275px)';"
screeny
 

@driver.execute_script "var origOverflow = document.documentElement.style.overflow; document.documentElement.style.overflow = \"\"; return origOverflow"
@driver.execute_script "document.documentElement.style['-webkit-transform'] = '';document.documentElement.style['transform'] = '';"
screeny
 

@driver.execute_script "var scrollWidth = document.documentElement.scrollWidth; var bodyScrollWidth = document.body.scrollWidth; var totalWidth = Math.max(scrollWidth, bodyScrollWidth); var clientHeight = document.documentElement.clientHeight; var bodyClientHeight = document.body.clientHeight; var scrollHeight = document.documentElement.scrollHeight; var bodyScrollHeight = document.body.scrollHeight; var maxDocElementHeight = Math.max(clientHeight, scrollHeight); var maxBodyHeight = Math.max(bodyClientHeight, bodyScrollHeight); var totalHeight = Math.max(maxDocElementHeight, maxBodyHeight); return [totalWidth, totalHeight];"
@driver.execute_script "return window.devicePixelRatio"
@driver.execute_script "var origOverflow = document.documentElement.style.overflow; document.documentElement.style.overflow = \"hidden\"; return origOverflow"
puts @driver.execute_script "return { 'transform': document.documentElement.style['transform'],'-webkit-transform': document.documentElement.style['-webkit-transform'], }"

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -0px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -0px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -325px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -325px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -650px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -650px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -975px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -975px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1300px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1300px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1625px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1625px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1950px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1950px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -2275px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -2275px)';"
screeny
 


@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -325px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -325px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -650px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -650px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -975px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -975px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1300px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1300px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1625px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1625px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -1950px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -1950px)';"
screeny
 

@driver.execute_script "document.documentElement.style['transform'] = 'translate(-0px, -2275px)';document.documentElement.style['-webkit-transform'] = 'translate(-0px, -2275px)';"
screeny
 




@driver.execute_script "var origOverflow = document.documentElement.style.overflow; document.documentElement.style.overflow = \"\"; return origOverflow"
@driver.execute_script "document.documentElement.style['-webkit-transform'] = '';document.documentElement.style['transform'] = '';"
puts @driver.title 
STDERR.puts "Quitting"
@driver.quit 